apiVersion: batch/v1
kind: CronJob
metadata:
  name: mlops-iris-retrain
spec:
  schedule: "0 * * * *"   # every hour (for demo)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: retrain-container
              image: your-docker-username/endtoend-mlops:latest
              command: ["python", "ml_pipeline.py"]
              volumeMounts:
                - name: model-storage
                  mountPath: /app/models
          volumes:
            - name: model-storage
              persistentVolumeClaim:
                claimName: model-pvc
          restartPolicy: OnFailure
